### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by timothe-j** [WikiPlag/wiki_data_fetcher#1]
For convenience and a more specific task management we want to have a Command Line Interface

It should also be possible to pass username and password via parameters

is blocked by #3

**Comment by maiktheknife** [comment]
done on 01e5070dc7a44635bdc1edfa5b863d568e2b0a0f

**Comment by maiktheknife** [comment]
done on 01e5070dc7a44635bdc1edfa5b863d568e2b0a0f
